function(nre_enable_warnings target)
    if (MSVC)
        target_compile_options(${target} PRIVATE /W4 /permissive- /w44265 /w44062 /external:W0)
        target_compile_options(${target} PRIVATE /EHsc)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wsign-conversion)
        if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
            target_compile_options(${target} PRIVATE -Wdocumentation -Wthread-safety)
        endif()
    endif()
endfunction()
